### ISSUE TITLE
create site structure

### ISSUE THREAD

**Issue by ElenaSpb** [Brain-up/auto-tests-python#34]
result https://github.com/Brain-up/auto-tests-python/wiki/Site-Structure 

https://docs.google.com/spreadsheets/d/1_GUmCWoisu6S3cgshljg5Uk-QSy6abcN69pv25ni4Ts/edit#gid=0
move to our cloud please

https://docs.google.com/spreadsheets/d/1zQdQwu4IwF0nzbj2BdxnJ-8fKRZ6jzl7Sy71FszfK0g/edit?usp=sharing

**Comment by ElenaSpb** [comment]
1 site structure as a tree
2 replace codes as c06 by short text

**Comment by alena-krauchuk** [comment]
Change page titles

**Comment by alena-krauchuk** [comment]
Page titles have been changed
