### ISSUE TITLE
Autotests: USED RESOURCES page

### ISSUE THREAD

**Issue by ElenaSpb** [Brain-up/auto-tests-python#39]
Check web elements, excluding header and footer, on the 'Used Resources' page.
The page index in the [Site Structure](https://github.com/Brain-up/auto-tests-python/wiki/Site-Structure): A.05.05
The page url: https://brainup.site/used-resources

**Comment by alena-krauchuk** [comment]
The issue was closed by technical error.

**Comment by alena-krauchuk** [comment]
Reopened for code refactoring
